### PR TITLE
Added Dutch translation and renamed XBMC to Kodi

### PR DESCRIPTION
**Pull request by PanderMusubi**
Please also consider renaming the add-on to have kodi in its name and not xbmc anymore.

### CODE REVIEW

**Comment by PanderMusubi** [comment]
Changing http to https was done according to advice of SomaFM, performance on https for channels.xml is better.

**Comment by Oderik** [comment]
Great, thanks for your contribution!

You now have push access to the repository.

**Comment by Oderik** [comment]
I haven't requested an update to the kodi repository yet. Please remind me if it takes me too long to do accomplish that or trigger an update by yourself if you like. ;) If you do, you should update the version number first.

**Comment by PanderMusubi** [comment]
Thanks. If you can explain me how to trigger an update I am willing to do that.

**Comment by PanderMusubi** [comment]
FYI, see also https://github.com/PanderMusubi/online-radio-channels

**Comment by PanderMusubi** [comment]
I will be making a fork of this project to reuse your plugin under the same license for http://intergalacticfm.com if that is fine by you.

**Comment by Oderik** [comment]
Yes, it's OK!
Am 03.11.2015 5:25 nachm. schrieb Pander <notifications@github.com>:I will be making a fork of this project to reuse your plugin under the same license for http://intergalacticfm.com if that is fine by you.

**Pull request merged**
